default:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: training-ilker
      dataset:  ga_analysis # You can also use "schema" here
      threads: 1
      job_creation_timeout_seconds: 30
      job_execution_timeout_seconds: 600
      job_retries: 5
      job_retry_deadline_seconds: 1200
      location: US

      # If a query would bill more than a gigabyte of data, then
      # BigQuery will reject the query
      # maximum_bytes_billed: 1000000000

      scopes:
        - https://www.googleapis.com/auth/bigquery
        #- https://www.googleapis.com/auth/cloud-platform
        #- https://www.googleapis.com/auth/drive




